import { useContext } from "react";
import { DeepLinkIapContext } from "./DeepLinkIapProvider";

const useDeepLinkIapProvider = () => {
  const {
    referrerLink,
    userId,
    validatePurchaseWithIapticAPI,
    storeExpectedStoreTransaction,
    returnUserAccountTokenAndStoreExpectedTransaction,
    returnInsertAffiliateIdentifier,
    isAffiliateAttributionValid,
    getAffiliateStoredDate,
    getAffiliateExpiryTimestamp,
    trackEvent,
    setShortCode,
    getAffiliateDetails,
    getAffiliateLookupResult,
    setInsertAffiliateIdentifier,
    setInsertAffiliateIdentifierChangeCallback,
    handleInsertLinks,
    initialize,
    setLogger,
    isInitialized,
    OfferCode,
    createAffiliateForUser,
    verifyAffiliateCode,
    setReferrerAccount,
    getMyAffiliateDetails,
    isUserAnAffiliate,
    signOutAffiliate,
    getReferralProgramConfig,
    shareReferralLink,
  } = useContext(DeepLinkIapContext);

  return {
    referrerLink,
    userId,
    validatePurchaseWithIapticAPI,
    storeExpectedStoreTransaction,
    returnUserAccountTokenAndStoreExpectedTransaction,
    returnInsertAffiliateIdentifier,
    isAffiliateAttributionValid,
    getAffiliateStoredDate,
    getAffiliateExpiryTimestamp,
    trackEvent,
    setShortCode,
    getAffiliateDetails,
    getAffiliateLookupResult,
    setInsertAffiliateIdentifier,
    setInsertAffiliateIdentifierChangeCallback,
    handleInsertLinks,
    initialize,
    setLogger,
    isInitialized,
    OfferCode,
    createAffiliateForUser,
    verifyAffiliateCode,
    setReferrerAccount,
    getMyAffiliateDetails,
    isUserAnAffiliate,
    signOutAffiliate,
    getReferralProgramConfig,
    shareReferralLink,
  };
};

export default useDeepLinkIapProvider;
